{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pcs-arrow-ipc/0.1.0/pcs-arrow-ipc-0.1.0.module",
    "group": "io.github.nassor",
    "module": "pcs-arrow-ipc",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "pcs-arrow-ipc-wasm-wasi-0.1.0.klib",
          "url": "pcs-arrow-ipc-wasm-wasi-0.1.0.klib",
          "size": 38945,
          "sha512": "6b25be25270cb91367e7bcbda08f4fd69371f0c1aa2d84cb033f61435641a8e631f916607bef0fbaf90491b7ef6d4f91006af953f300471633c00815a16958e8",
          "sha256": "199cf342c38408183206e93a7e88f6493ad3d5a8fde9b85203d93978c35adaac",
          "sha1": "08240a400ab04dc75143956bc9124e4a8076cd07",
          "md5": "75418f745c4967400c4a5cb786a4b69c"
        }
      ]
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "pcs-arrow-ipc-wasm-wasi-0.1.0.klib",
          "url": "pcs-arrow-ipc-wasm-wasi-0.1.0.klib",
          "size": 38945,
          "sha512": "6b25be25270cb91367e7bcbda08f4fd69371f0c1aa2d84cb033f61435641a8e631f916607bef0fbaf90491b7ef6d4f91006af953f300471633c00815a16958e8",
          "sha256": "199cf342c38408183206e93a7e88f6493ad3d5a8fde9b85203d93978c35adaac",
          "sha1": "08240a400ab04dc75143956bc9124e4a8076cd07",
          "md5": "75418f745c4967400c4a5cb786a4b69c"
        }
      ]
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "files": [
        {
          "name": "pcs-arrow-ipc-wasm-wasi-0.1.0-sources.jar",
          "url": "pcs-arrow-ipc-wasm-wasi-0.1.0-sources.jar",
          "size": 9072,
          "sha512": "5c029d42731bedb0a7f053f2a7c0cc1093e20db7624d4424bb2106c09c1693dec48950438f561dc636d2bfa542ccbb50b61b393e2a944df4c1924ea56e8d90e6",
          "sha256": "21eaba1a827f50125d5a6c24d885a2925529ac9de0b5af6ac289ff1ea03638a3",
          "sha1": "1733f3ac20179897c12ba5114e86a5649514c532",
          "md5": "c313ab88c56881d7beb397be2b87c3b4"
        }
      ]
    }
  ]
}
