// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod pcs {
    pub mod pipeline {
        /// Host capabilities the guest may call during init or run-batch.
        /// Deliberately minimal in v0.1.0: logging, metric counters, static config read.
        /// NO filesystem, NO network, NO clock (epoch-driven cancellation only).
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod host_io {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum LogLevel {
                Trace,
                Debug,
                Info,
                Warn,
                Error,
            }
            impl ::core::fmt::Debug for LogLevel {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        LogLevel::Trace => f.debug_tuple("LogLevel::Trace").finish(),
                        LogLevel::Debug => f.debug_tuple("LogLevel::Debug").finish(),
                        LogLevel::Info => f.debug_tuple("LogLevel::Info").finish(),
                        LogLevel::Warn => f.debug_tuple("LogLevel::Warn").finish(),
                        LogLevel::Error => f.debug_tuple("LogLevel::Error").finish(),
                    }
                }
            }
            impl LogLevel {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> LogLevel {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => LogLevel::Trace,
                        1 => LogLevel::Debug,
                        2 => LogLevel::Info,
                        3 => LogLevel::Warn,
                        4 => LogLevel::Error,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Structured log line bridged to tracing on the host.
            pub fn log(level: LogLevel, target: &str, message: &str) -> () {
                unsafe {
                    let vec0 = target;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = message;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "pcs:pipeline/host-io@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "log"]
                        fn wit_import2(
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(
                        _: i32,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import2(
                            level.clone() as i32,
                            ptr0.cast_mut(),
                            len0,
                            ptr1.cast_mut(),
                            len1,
                        )
                    };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Increment or observe a named metric. Host routes to prometheus.
            /// Value is f64 to cover counters, gauges, and histograms.
            pub fn metric(name: &str, value: f64) -> () {
                unsafe {
                    let vec0 = name;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "pcs:pipeline/host-io@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "metric"]
                        fn wit_import1(_: *mut u8, _: usize, _: f64);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize, _: f64) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0.cast_mut(), len0, _rt::as_f64(&value)) };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Pull a string-typed config value the host injected via
            /// `pipeline.wasm.config` in service YAML. Returns none if absent.
            /// Guest is expected to parse numerics itself.
            pub fn get_config(key: &str) -> Option<_rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = key;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "pcs:pipeline/host-io@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "get-config"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result7 = match l3 {
                        0 => None,
                        1 => {
                            let e = {
                                let l4 = *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l5 = *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len6 = l5;
                                let bytes6 = _rt::Vec::from_raw_parts(
                                    l4.cast(),
                                    len6,
                                    len6,
                                );
                                _rt::string_lift(bytes6)
                            };
                            Some(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result7
                }
            }
        }
        /// NOTE: intentionally no `required-host-io-version` field on pipeline-descriptor
        /// in v0.1.0. The WIT package version (`@0.1.0`) already signals host-io
        /// compatibility; adding a forward-compat knob before we know what backward
        /// incompat looks like is speculative. Revisit for v0.2 if host-io grows.
        /// Types shared by the pipeline interface.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            /// Arrow IPC stream bytes (schema + batches). Host serializes a Dataset
            /// on input; guest re-serializes the (possibly mutated) Dataset on output.
            pub type IpcBytes = _rt::Vec<u8>;
            /// Opaque guest-owned checkpoint blob. Host persists verbatim via
            /// pcs-core CheckpointStore; guest owns the layout.
            pub type Checkpoint = _rt::Vec<u8>;
            /// One component declared by the guest pipeline. `arrow-schema-ipc`
            /// is the Arrow IPC schema-message bytes for that component's RecordBatch
            /// shape. Host validates source/sink target_component names against this
            /// list at load time.
            #[derive(Clone)]
            pub struct ComponentDescriptor {
                pub name: _rt::String,
                pub arrow_schema_ipc: _rt::Vec<u8>,
            }
            impl ::core::fmt::Debug for ComponentDescriptor {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ComponentDescriptor")
                        .field("name", &self.name)
                        .field("arrow-schema-ipc", &self.arrow_schema_ipc)
                        .finish()
                }
            }
            /// Stable identity of the pipeline. Host gates config + checkpoint
            /// compatibility on this. `schema-fingerprint` is computed from the
            /// concatenation of all component schemas (see pcs-core SchemaRegistry).
            #[derive(Clone)]
            pub struct PipelineDescriptor {
                pub name: _rt::String,
                pub version: _rt::String,
                pub components: _rt::Vec<ComponentDescriptor>,
                pub stateful: bool,
                pub schema_fingerprint: _rt::String,
            }
            impl ::core::fmt::Debug for PipelineDescriptor {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("PipelineDescriptor")
                        .field("name", &self.name)
                        .field("version", &self.version)
                        .field("components", &self.components)
                        .field("stateful", &self.stateful)
                        .field("schema-fingerprint", &self.schema_fingerprint)
                        .finish()
                }
            }
            /// Lightweight metrics the guest reports after each batch. Host surfaces
            /// to prometheus via host-io::metric.
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct RunMetrics {
                pub wall_ns: u64,
                pub rows_in: u64,
                pub rows_out: u64,
                pub systems_run: u32,
                pub retries: u32,
            }
            impl ::core::fmt::Debug for RunMetrics {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("RunMetrics")
                        .field("wall-ns", &self.wall_ns)
                        .field("rows-in", &self.rows_in)
                        .field("rows-out", &self.rows_out)
                        .field("systems-run", &self.systems_run)
                        .field("retries", &self.retries)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct RunResult {
                pub output: IpcBytes,
                pub checkpoint: Option<Checkpoint>,
                pub metrics: RunMetrics,
            }
            impl ::core::fmt::Debug for RunResult {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("RunResult")
                        .field("output", &self.output)
                        .field("checkpoint", &self.checkpoint)
                        .field("metrics", &self.metrics)
                        .finish()
                }
            }
            /// Structured errors so host can distinguish "release claim and retry"
            /// from "ack claim and surface to operator".
            ///
            /// Variant naming matches DistributedRunner vocabulary:
            /// `retryable` → runner calls `release_claim`
            /// `permanent` → runner calls `ack_claim`
            ///
            /// v0.1.0 is deliberately a three-arm variant. A `host-denied(string)`
            /// arm for host-io capability refusals was considered and rejected:
            /// v0.1.0's host-io surface (log / metric / get-config) cannot fail,
            /// so the slot would be dead weight. When v0.2 grows the host-io
            /// surface (e.g. filesystem or network), the WIT package version bump
            /// to 0.2.0 is itself the right moment to add the variant — no need
            /// to reserve it speculatively here.
            #[derive(Clone)]
            pub enum RunError {
                /// Transient — retry-worthy failure. Host releases claim, retries
                /// next tick. Maps to `release_claim`.
                Retryable(_rt::String),
                /// Permanent — bad input shape, guest logic bug, unknown error.
                /// Host acks claim, logs, surfaces to /status. Maps to `ack_claim`.
                Permanent(_rt::String),
                /// Fingerprint mismatch. Emitted ONLY from `restore()`. `run-batch`
                /// MUST NOT emit this; any mid-batch schema error is folded into
                /// `permanent`. Host refuses to replay.
                SchemaMismatch(_rt::String),
            }
            impl ::core::fmt::Debug for RunError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        RunError::Retryable(e) => {
                            f.debug_tuple("RunError::Retryable").field(e).finish()
                        }
                        RunError::Permanent(e) => {
                            f.debug_tuple("RunError::Permanent").field(e).finish()
                        }
                        RunError::SchemaMismatch(e) => {
                            f.debug_tuple("RunError::SchemaMismatch").field(e).finish()
                        }
                    }
                }
            }
            impl ::core::fmt::Display for RunError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }
            impl std::error::Error for RunError {}
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod pcs {
        pub mod pipeline {
            /// The sole guest export. All functions are sync from the WIT perspective;
            /// the host wraps each call in spawn_blocking + epoch interruption.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod pipeline {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type PipelineDescriptor = super::super::super::super::pcs::pipeline::types::PipelineDescriptor;
                pub type IpcBytes = super::super::super::super::pcs::pipeline::types::IpcBytes;
                pub type Checkpoint = super::super::super::super::pcs::pipeline::types::Checkpoint;
                pub type RunResult = super::super::super::super::pcs::pipeline::types::RunResult;
                pub type RunError = super::super::super::super::pcs::pipeline::types::RunError;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_describe_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::describe();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let super::super::super::super::pcs::pipeline::types::PipelineDescriptor {
                        name: name2,
                        version: version2,
                        components: components2,
                        stateful: stateful2,
                        schema_fingerprint: schema_fingerprint2,
                    } = result0;
                    let vec3 = (name2.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr1.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    let vec4 = (version2.into_bytes()).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *ptr1.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *ptr1
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr4.cast_mut();
                    let vec8 = components2;
                    let len8 = vec8.len();
                    let layout8 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec8.len() * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result8 = if layout8.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout8).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout8);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec8.into_iter().enumerate() {
                        let base = result8
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let super::super::super::super::pcs::pipeline::types::ComponentDescriptor {
                                name: name5,
                                arrow_schema_ipc: arrow_schema_ipc5,
                            } = e;
                            let vec6 = (name5.into_bytes()).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *base.add(0).cast::<*mut u8>() = ptr6.cast_mut();
                            let vec7 = (arrow_schema_ipc5).into_boxed_slice();
                            let ptr7 = vec7.as_ptr().cast::<u8>();
                            let len7 = vec7.len();
                            ::core::mem::forget(vec7);
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len7;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr7.cast_mut();
                        }
                    }
                    *ptr1.add(5 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len8;
                    *ptr1
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = result8;
                    *ptr1.add(6 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (match stateful2 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    let vec9 = (schema_fingerprint2.into_bytes()).into_boxed_slice();
                    let ptr9 = vec9.as_ptr().cast::<u8>();
                    let len9 = vec9.len();
                    ::core::mem::forget(vec9);
                    *ptr1.add(8 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len9;
                    *ptr1
                        .add(7 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr9.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_describe<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                    let l2 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l3 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l2, l3, 1);
                    let l4 = *arg0
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l5 = *arg0
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base11 = l4;
                    let len11 = l5;
                    for i in 0..len11 {
                        let base = base11
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l6 = *base.add(0).cast::<*mut u8>();
                            let l7 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l6, l7, 1);
                            let l8 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l9 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base10 = l8;
                            let len10 = l9;
                            _rt::cabi_dealloc(base10, len10 * 1, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base11,
                        len11 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let l12 = *arg0
                        .add(7 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l13 = *arg0
                        .add(8 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l12, l13, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_init_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::init(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(_) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec3 = (e.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_init<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_run_batch_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: i32,
                    arg3: *mut u8,
                    arg4: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let result2 = T::run_batch(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                        match arg2 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len1 = arg4;
                                    _rt::Vec::from_raw_parts(arg3.cast(), len1, len1)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Ok(e) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                            let super::super::super::super::pcs::pipeline::types::RunResult {
                                output: output4,
                                checkpoint: checkpoint4,
                                metrics: metrics4,
                            } = e;
                            let vec5 = (output4).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr3
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr3.add(8).cast::<*mut u8>() = ptr5.cast_mut();
                            match checkpoint4 {
                                Some(e) => {
                                    *ptr3
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec6 = (e).into_boxed_slice();
                                    let ptr6 = vec6.as_ptr().cast::<u8>();
                                    let len6 = vec6.len();
                                    ::core::mem::forget(vec6);
                                    *ptr3
                                        .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len6;
                                    *ptr3
                                        .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr6.cast_mut();
                                }
                                None => {
                                    *ptr3
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                            let super::super::super::super::pcs::pipeline::types::RunMetrics {
                                wall_ns: wall_ns7,
                                rows_in: rows_in7,
                                rows_out: rows_out7,
                                systems_run: systems_run7,
                                retries: retries7,
                            } = metrics4;
                            *ptr3
                                .add(16 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<i64>() = _rt::as_i64(wall_ns7);
                            *ptr3
                                .add(24 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<i64>() = _rt::as_i64(rows_in7);
                            *ptr3
                                .add(32 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<i64>() = _rt::as_i64(rows_out7);
                            *ptr3
                                .add(40 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(systems_run7);
                            *ptr3
                                .add(44 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(retries7);
                        }
                        Err(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            use super::super::super::super::pcs::pipeline::types::RunError as V11;
                            match e {
                                V11::Retryable(e) => {
                                    *ptr3.add(8).cast::<u8>() = (0i32) as u8;
                                    let vec8 = (e.into_bytes()).into_boxed_slice();
                                    let ptr8 = vec8.as_ptr().cast::<u8>();
                                    let len8 = vec8.len();
                                    ::core::mem::forget(vec8);
                                    *ptr3
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len8;
                                    *ptr3
                                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr8.cast_mut();
                                }
                                V11::Permanent(e) => {
                                    *ptr3.add(8).cast::<u8>() = (1i32) as u8;
                                    let vec9 = (e.into_bytes()).into_boxed_slice();
                                    let ptr9 = vec9.as_ptr().cast::<u8>();
                                    let len9 = vec9.len();
                                    ::core::mem::forget(vec9);
                                    *ptr3
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len9;
                                    *ptr3
                                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr9.cast_mut();
                                }
                                V11::SchemaMismatch(e) => {
                                    *ptr3.add(8).cast::<u8>() = (2i32) as u8;
                                    let vec10 = (e.into_bytes()).into_boxed_slice();
                                    let ptr10 = vec10.as_ptr().cast::<u8>();
                                    let len10 = vec10.len();
                                    ::core::mem::forget(vec10);
                                    *ptr3
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len10;
                                    *ptr3
                                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr10.cast_mut();
                                }
                            }
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_run_batch<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0.add(8).cast::<*mut u8>();
                            let l2 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                            let l4 = i32::from(
                                *arg0
                                    .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l4 {
                                0 => {}
                                _ => {
                                    let l5 = *arg0
                                        .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l6 = *arg0
                                        .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let base7 = l5;
                                    let len7 = l6;
                                    _rt::cabi_dealloc(base7, len7 * 1, 1);
                                }
                            }
                        }
                        _ => {
                            let l8 = i32::from(*arg0.add(8).cast::<u8>());
                            match l8 {
                                0 => {
                                    let l9 = *arg0
                                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l10 = *arg0
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l9, l10, 1);
                                }
                                1 => {
                                    let l11 = *arg0
                                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l12 = *arg0
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l11, l12, 1);
                                }
                                _ => {
                                    let l13 = *arg0
                                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l14 = *arg0
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l13, l14, 1);
                                }
                            }
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_snapshot_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::snapshot();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(e) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                            let vec2 = (e).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr2.cast_mut();
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let vec3 = (e.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_snapshot<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                        }
                        _ => {
                            let l4 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_restore_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let result1 = T::restore(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(_) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec3 = (e.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_restore<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Called once at load time. Host validates the descriptor against
                    /// ServiceConfig (declared components cover sources/sinks, schema
                    /// fingerprint matches any persisted checkpoint).
                    fn describe() -> PipelineDescriptor;
                    /// Called once after describe(), before any run-batch. Host passes the
                    /// full `pipeline.wasm.config` YAML block as a JSON string. Guest parses
                    /// and stores locally. Returning err aborts service startup.
                    fn init(config: _rt::String) -> Result<(), _rt::String>;
                    /// The hot path. Host marshals the partition batch to Arrow IPC and
                    /// hands it in alongside any prior checkpoint. Guest runs its internal
                    /// Pipeline::run_on DAG against a fresh Dataset, returns IPC bytes +
                    /// optional new checkpoint + metrics.
                    ///
                    /// Invariant: run-batch MUST NOT return run-error::schema-mismatch.
                    /// Schema/fingerprint validation is a startup concern and lives only
                    /// in describe() + restore(). A mismatch surfacing mid-batch is a
                    /// guest bug and must be collapsed to `permanent`.
                    fn run_batch(
                        input: IpcBytes,
                        prior: Option<Checkpoint>,
                    ) -> Result<RunResult, RunError>;
                    /// Emit a point-in-time checkpoint without running a batch. Used by
                    /// CheckpointStrategy::EveryNStages path if the guest chooses to snapshot
                    /// between ticks. May return err if the guest has no persistent state.
                    fn snapshot() -> Result<Checkpoint, _rt::String>;
                    /// Restore from a persisted checkpoint during cold-start recovery.
                    /// Returning err forces the host to refuse startup. The `schema-mismatch`
                    /// variant of run-error is conceptually at home here, but restore uses a
                    /// plain string error because the host can't act differently on mismatch
                    /// vs. other restore failures at cold-start — both abort startup.
                    fn restore(cp: Checkpoint) -> Result<(), _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_pcs_pipeline_pipeline_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "pcs:pipeline/pipeline@0.1.0#describe")] unsafe extern "C" fn
                        export_describe() -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_describe_cabi::<$ty > () } } #[unsafe (export_name =
                        "cabi_post_pcs:pipeline/pipeline@0.1.0#describe")] unsafe extern
                        "C" fn _post_return_describe(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_describe::<$ty > (arg0) } }
                        #[unsafe (export_name = "pcs:pipeline/pipeline@0.1.0#init")]
                        unsafe extern "C" fn export_init(arg0 : * mut u8, arg1 : usize,)
                        -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_init_cabi::<$ty > (arg0, arg1) } } #[unsafe (export_name
                        = "cabi_post_pcs:pipeline/pipeline@0.1.0#init")] unsafe extern
                        "C" fn _post_return_init(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_init::<$ty > (arg0) } }
                        #[unsafe (export_name = "pcs:pipeline/pipeline@0.1.0#run-batch")]
                        unsafe extern "C" fn export_run_batch(arg0 : * mut u8, arg1 :
                        usize, arg2 : i32, arg3 : * mut u8, arg4 : usize,) -> * mut u8 {
                        unsafe { $($path_to_types)*:: _export_run_batch_cabi::<$ty >
                        (arg0, arg1, arg2, arg3, arg4) } } #[unsafe (export_name =
                        "cabi_post_pcs:pipeline/pipeline@0.1.0#run-batch")] unsafe extern
                        "C" fn _post_return_run_batch(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_run_batch::<$ty > (arg0) } }
                        #[unsafe (export_name = "pcs:pipeline/pipeline@0.1.0#snapshot")]
                        unsafe extern "C" fn export_snapshot() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_snapshot_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_pcs:pipeline/pipeline@0.1.0#snapshot")] unsafe extern
                        "C" fn _post_return_snapshot(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_snapshot::<$ty > (arg0) } }
                        #[unsafe (export_name = "pcs:pipeline/pipeline@0.1.0#restore")]
                        unsafe extern "C" fn export_restore(arg0 : * mut u8, arg1 :
                        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_restore_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name = "cabi_post_pcs:pipeline/pipeline@0.1.0#restore")]
                        unsafe extern "C" fn _post_return_restore(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_restore::<$ty >
                        (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_pcs_pipeline_pipeline_0_1_0_cabi;
                #[repr(align(8))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 48 + 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 48
                        + 4 * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::alloc;
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_pcs_pipeline_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::pcs::pipeline::pipeline::__export_pcs_pipeline_pipeline_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::pcs::pipeline::pipeline);
    };
}
#[doc(inline)]
pub(crate) use __export_pcs_pipeline_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.41.0:pcs:pipeline@0.1.0:pcs-pipeline:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1105] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xce\x07\x01A\x02\x01\
A\x0b\x01B\x09\x01m\x05\x05trace\x05debug\x04info\x04warn\x05error\x04\0\x09log-\
level\x03\0\0\x01@\x03\x05level\x01\x06targets\x07messages\x01\0\x04\0\x03log\x01\
\x02\x01@\x02\x04names\x05valueu\x01\0\x04\0\x06metric\x01\x03\x01ks\x01@\x01\x03\
keys\0\x04\x04\0\x0aget-config\x01\x05\x03\0\x1apcs:pipeline/host-io@0.1.0\x05\0\
\x01B\x11\x01p}\x04\0\x09ipc-bytes\x03\0\0\x01p}\x04\0\x0acheckpoint\x03\0\x02\x01\
p}\x01r\x02\x04names\x10arrow-schema-ipc\x04\x04\0\x14component-descriptor\x03\0\
\x05\x01p\x06\x01r\x05\x04names\x07versions\x0acomponents\x07\x08stateful\x7f\x12\
schema-fingerprints\x04\0\x13pipeline-descriptor\x03\0\x08\x01r\x05\x07wall-nsw\x07\
rows-inw\x08rows-outw\x0bsystems-runy\x07retriesy\x04\0\x0brun-metrics\x03\0\x0a\
\x01k\x03\x01r\x03\x06output\x01\x0acheckpoint\x0c\x07metrics\x0b\x04\0\x0arun-r\
esult\x03\0\x0d\x01q\x03\x09retryable\x01s\0\x09permanent\x01s\0\x0fschema-misma\
tch\x01s\0\x04\0\x09run-error\x03\0\x0f\x03\0\x18pcs:pipeline/types@0.1.0\x05\x01\
\x02\x03\0\x01\x13pipeline-descriptor\x02\x03\0\x01\x09ipc-bytes\x02\x03\0\x01\x0a\
checkpoint\x02\x03\0\x01\x0arun-result\x02\x03\0\x01\x09run-error\x01B\x18\x02\x03\
\x02\x01\x02\x04\0\x13pipeline-descriptor\x03\0\0\x02\x03\x02\x01\x03\x04\0\x09i\
pc-bytes\x03\0\x02\x02\x03\x02\x01\x04\x04\0\x0acheckpoint\x03\0\x04\x02\x03\x02\
\x01\x05\x04\0\x0arun-result\x03\0\x06\x02\x03\x02\x01\x06\x04\0\x09run-error\x03\
\0\x08\x01@\0\0\x01\x04\0\x08describe\x01\x0a\x01j\0\x01s\x01@\x01\x06configs\0\x0b\
\x04\0\x04init\x01\x0c\x01k\x05\x01j\x01\x07\x01\x09\x01@\x02\x05input\x03\x05pr\
ior\x0d\0\x0e\x04\0\x09run-batch\x01\x0f\x01j\x01\x05\x01s\x01@\0\0\x10\x04\0\x08\
snapshot\x01\x11\x01@\x01\x02cp\x05\0\x0b\x04\0\x07restore\x01\x12\x04\0\x1bpcs:\
pipeline/pipeline@0.1.0\x05\x07\x04\0\x1fpcs:pipeline/pcs-pipeline@0.1.0\x04\0\x0b\
\x12\x01\0\x0cpcs-pipeline\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwi\
t-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
