{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pcs-sdk-kt/0.1.0/pcs-sdk-kt-0.1.0.module",
    "group": "io.github.nassor",
    "module": "pcs-sdk-kt",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "pcs-sdk-kt-jvm-0.1.0.jar",
          "url": "pcs-sdk-kt-jvm-0.1.0.jar",
          "size": 76204,
          "sha512": "ccbfae4f9a8bd51f6cd2b94c82c2ba9f27080b27c5e5abb8f321e941dc75079e385c1c4d0ab542a4cdcb055a56c813a8818e218509232d1872ef19bd4bbcdcea",
          "sha256": "1ac15b8ed9cd79af9f634a0a311304f5267e696b80381c1ba6fd3a4e27c24259",
          "sha1": "6e66364134777b1bd1e3edf5b00160bf9163af1d",
          "md5": "821840ea3d06a8f0e050e3aebcf3d344"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "pcs-sdk-kt-jvm-0.1.0.jar",
          "url": "pcs-sdk-kt-jvm-0.1.0.jar",
          "size": 76204,
          "sha512": "ccbfae4f9a8bd51f6cd2b94c82c2ba9f27080b27c5e5abb8f321e941dc75079e385c1c4d0ab542a4cdcb055a56c813a8818e218509232d1872ef19bd4bbcdcea",
          "sha256": "1ac15b8ed9cd79af9f634a0a311304f5267e696b80381c1ba6fd3a4e27c24259",
          "sha1": "6e66364134777b1bd1e3edf5b00160bf9163af1d",
          "md5": "821840ea3d06a8f0e050e3aebcf3d344"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "pcs-sdk-kt-jvm-0.1.0-sources.jar",
          "url": "pcs-sdk-kt-jvm-0.1.0-sources.jar",
          "size": 25796,
          "sha512": "ed0f6b800a82de4978ded97406d6353dbae8239fed3e580d27a8f97d550b449de71d037d7f4ab75c4559e1d964dd1a87bb2a4d3277651bd62be15e8111a6d57b",
          "sha256": "ec7930e25c854b9c3860f2f78c2ddc2686a3a7a71e6d5626c2800c06fc9b6f42",
          "sha1": "05d9bc46b60bc245ffea9a3fc194818f1dc483eb",
          "md5": "9038a51dbe14600fa078fc3c1be63528"
        }
      ]
    }
  ]
}
