{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pcs-arrow-ipc/0.1.0/pcs-arrow-ipc-0.1.0.module",
    "group": "io.github.nassor",
    "module": "pcs-arrow-ipc",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "pcs-arrow-ipc-jvm-0.1.0.jar",
          "url": "pcs-arrow-ipc-jvm-0.1.0.jar",
          "size": 28394,
          "sha512": "a8f37b67d1d0c4fa87d2d537c9c1a93172ae8a46b26566a36b1dc56ad2750589213110c821789a49785fc856c9e75a95cb41d14f96807cf230ec7ac195ad0389",
          "sha256": "7be4ef7a116225bcde31c3a84c21ddd37eb17a2253c4f4f38e952a2e7ebae948",
          "sha1": "2aeae3b6d9fb6953d6fed1f4535b2a2368b20d1e",
          "md5": "5ec7095dda8f6d6e48a1d9d54673c494"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "pcs-arrow-ipc-jvm-0.1.0.jar",
          "url": "pcs-arrow-ipc-jvm-0.1.0.jar",
          "size": 28394,
          "sha512": "a8f37b67d1d0c4fa87d2d537c9c1a93172ae8a46b26566a36b1dc56ad2750589213110c821789a49785fc856c9e75a95cb41d14f96807cf230ec7ac195ad0389",
          "sha256": "7be4ef7a116225bcde31c3a84c21ddd37eb17a2253c4f4f38e952a2e7ebae948",
          "sha1": "2aeae3b6d9fb6953d6fed1f4535b2a2368b20d1e",
          "md5": "5ec7095dda8f6d6e48a1d9d54673c494"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "pcs-arrow-ipc-jvm-0.1.0-sources.jar",
          "url": "pcs-arrow-ipc-jvm-0.1.0-sources.jar",
          "size": 9072,
          "sha512": "5c029d42731bedb0a7f053f2a7c0cc1093e20db7624d4424bb2106c09c1693dec48950438f561dc636d2bfa542ccbb50b61b393e2a944df4c1924ea56e8d90e6",
          "sha256": "21eaba1a827f50125d5a6c24d885a2925529ac9de0b5af6ac289ff1ea03638a3",
          "sha1": "1733f3ac20179897c12ba5114e86a5649514c532",
          "md5": "c313ab88c56881d7beb397be2b87c3b4"
        }
      ]
    }
  ]
}
